// CHEESE ASSEMBLY TEST 1:
// ADDING NUMBERS (ALSO POKE AND PRINT)

PUSH 3
ADD #4	// 3 + 4 = 7, SO STACK = [7]
PUSH 3	// STACK = [7, 3]
POKE 40	// STACK = [7]
ADD 40	// STACK = [10] - REMEMBER, WE'RE ADDING THE CONTENTS OF *ADDRESS* 40
PRINT	// TEST PASSES IF IT PRINTS 10

